/*
 * This source file was generated by the Gradle 'init' task
 */
package projectmyteam;

import javafx.application.Application;
import javafx.stage.Stage;

public class Main extends Application {
    @Override
    public void start(Stage primaryStage) {
        new LoginUI(primaryStage);
    }

    public static void main(String[] args) {
        launch(args);
    }

    public class Main {
        public static void main(String[] args) {
            ReservationSystem reservationSystem = new ReservationSystem(5);
    
            reservationSystem.reserveTable(2);
            reservationSystem.reserveTable(3);
            reservationSystem.displayAvailableTables();
    
            reservationSystem.cancelReservation(2);
            reservationSystem.displayAvailableTables();
        }
    }
    

}
