/*
 * This source file was generated by the Gradle 'init' task
 */
package projectmyteam;

import javafx.application.Application;
import javafx.stage.Stage;

public class Main {
    public static void account(String[] args) {
    @override
    public void start(Stage primaryStage) {
        new 
    }
}
