/*
 * This source file was generated by the Gradle 'init' task
 */
package projectmyteam;

import javafx.application.Application;
import javafx.stage.Stage;

public class Main {
    public static void account(String[] args) {
        Account acc = new Account();
        
        // Create account
        acc.createAccount("admin", "1234");
        
        // Test login
        System.out.println(acc.userLogin("admin", "1234")); // true
        System.out.println(acc.userLogin("admin", "wrong")); // false
        
        // Test check
        System.out.println(acc.userCheck()); // Owner
    }

    public static void cooking(String[] args) {
        Cooking cooking = new Cooking();

        cooking.startCooking("Pizza");
        cooking.updateIngrediant("Dough", 2);
        cooking.updateIngrediant("Tomato Sauce", 1);
        cooking.updateIngrediant("Cheese", 5);
        cooking.updateIngrediant("Pepperoni", 2);
        cooking.checkIngrediant();
        cooking.finishCooking(null);
        cooking.sendOrder(null);
    }

    public static void order(String[] args) {
        Order order = new Order();

        order.setOrderUser("Test");
        order.setOrderInfo("Pizza", 2);
        order.setOrderPrice(10.5f); // 10 each

        order.printOrderDetails();
    }

    public static void payment(String[] args) {
        Payment payment = new Payment();

        // Set price
        payment.orderPrice("User1", 100.0f);

        // Exact Payment
        System.out.println("Case 1: Exact Payment");
        System.out.println(payment.userPaid(100.0f)); // true
        System.out.println(payment.getChange()); // Thank you

        // Overpaid
        System.out.println("\nCase 2: Overpaid");
        System.out.println(payment.userPaid(120.0f)); // true
        System.out.println(payment.getChange()); // Change: 20

        // Underpaid
        System.out.println("\nCase 3: Underpaid");
        System.out.println(payment.userPaid(80.0f)); // false
        System.out.println(payment.getChange()); // Pay more 20
    }

    public static void restaurant(String[] args) {
        Restaurant myRestaurant = new Restaurant();

        // Add Name
        myRestaurant.createRestaurant("Test Restaurant");

        // Add foods
        myRestaurant.addFood("Pizza");

        // Add recipes
        myRestaurant.addRecipe("Dough, Tomato Sauce, Cheese, Pepperoni");

        // Add prices
        myRestaurant.addPrice("Pizza", 9.99f);

        // Debug 
        System.out.println("Testing completed. No errors found.");
    }

    public static void user(String[] args) {
        // User
        User user1 = new User("Test", 50.0f);

        // Test changing name
        user1.changeName("Bob");

        // Test adding balance
        user1.addBalance(20.0f);
        user1.addBalance(-5.0f);

        // Debug
        user1.printUserInfo();
    }
}
